stack/apps/stack/lib/stack_web/router.ex
defmodule StackWeb.Router do
  use StackWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", StackWeb do
    pipe_through :browser

    get "/", TopController, :index
    get "/lessons/form", LessonController, :form
    get "/stock_items", StockItemController, :index
    get "/stock_items/:id", StockItemController, :show
  end
end

stack/apps/stack/lib/stack/application.ex
defmodule Stack.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Stack.Repo,
      # Start the Telemetry supervisor
      StackWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Stack.PubSub},
      # Start the Endpoint (http/https)
      StackWeb.Endpoint
      # Start a worker by calling: Stack.Worker.start_link(arg)
      # {Stack.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Stack.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    StackWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

stack/apps/stack/lib/stack/fixture.ex
defmodule Stack.Fixture do
    import Ecto.Query, warn: false
    alias Stack.Repo
    alias Stack.Fixture.StockItem

    def list_stock_items do
        StockItem
        |> Ecto.Query.order_by(asc: :order_time)
        |> Repo.all()
    end

    def get_stock_item!(id) do
        Repo.get!(StockItem, id)
    end
end

stack/apps/stack/lib/stack/fixture/stock_item.ex
defmodule Stack.Fixture.StockItem do
  use Ecto.Schema
  import Ecto.Changeset

  schema "stock_items" do
    field :name, :string
    field :description, :string
    field :order_time, :utc_datetime
    
    timestamps(type: :utc_datetime_usec)
  end

  @doc false
  def changeset(stock_item, attrs) do
    stock_item
    |> cast(attrs, [])
    |> validate_required([])
  end
end

stack/apps/stack/lib/stack/repo.ex
defmodule Stack.Repo do
  use Ecto.Repo,
    otp_app: :stack,
    adapter: Ecto.Adapters.Postgres
end

stack/apps/stack/lib/stack_web/controllers/lesson_controller.ex
defmodule StackWeb.LessonController do
    use StackWeb, :controller
    
    def form(conn, _params) do
        render(conn, "form.html")
    end
end

stack/apps/stack/lib/stack_web/controllers/stock_item_controller.ex
defmodule StackWeb.StockItemController do
  use StackWeb, :controller
  alias Stack.Fixture

  def index(conn, _params) do
    stock_items = Fixture.list_stock_items()
    render(conn, "index.html", stock_items: stock_items)
  end

  def show(conn, %{"id" => id}) do
    stock_item = Fixture.get_stock_item!(id)
    render(conn, "show.html", stock_item: stock_item)
  end
end

stack/apps/stack/lib/stack_web/controllers/top_controller.ex
defmodule StackWeb.TopController do
  use StackWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

stack/apps/stack/lib/stack_web/views/error_view.ex
defmodule StackWeb.ErrorView do
  use StackWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

stack/apps/stack/lib/stack_web/views/layout_view.ex
defmodule StackWeb.LayoutView do
  use StackWeb, :view
end

stack/apps/stack/lib/stack_web/views/lesson_view.ex
defmodule StackWeb.LessonView do
    use StackWeb, :view
end

stack/apps/stack/lib/stack_web/views/stock_item_view.ex
defmodule StackWeb.StockItemView do
  use StackWeb, :view
  alias Timex.Format.DateTime.Formatters.Strftime
  
  def format_duration(item) do
    Enum.join([format_order_time(item), " "])
  end

  defp format_order_time(item) do
    Strftime.format!(item.order_time, "%m月%d日 %H:%M")
  end
end

stack/apps/stack/lib/stack_web/views/top_view.ex
defmodule StackWeb.TopView do
  use StackWeb, :view
end

stack/apps/stack/lib/stack_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Stack</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="icon" type="image/x-icon"
      href="<%= Routes.static_path(@conn, "/images/stack.ico") %>"/>
    <link rel="apple-touch-icon" type="image/x-icon"
      href="<%= Routes.static_path(@conn, "/images/clock256.png") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <h1>
        <%= link "Stack", to: Routes.top_path(@conn, :index, []) %>
      </h1>
    </header>
    <main>  
      <%= @inner_content %>
    </main>
    <footer>
      &copy; 2022 Ricky
    </footer>
  </body>
</html>

stack/apps/stack/lib/stack_web/templates/lesson/form.html.eex
<form action="/lessons/register">
    <div>
        <label for="user-name">ユーザー名</label>
        <input type="text" name="user_name" id="user-name">
    </div>
    <div>
        <input type="submit" value="登録">
    </div>
</form>

stack/apps/stack/lib/stack_web/templates/stock_item/index.html.eex
<div class="container-fluid stock-items">
    <%= for item <- @stock_items do %>
    <div class="row">
        <div class="col-12 col-md-4">
            <span class="stock-item-name">
                <%= link item.name,
                    to: Routes.stock_item_path(@conn, :show, item.id) %>
            </span>
        </div>
        <div class="col-12 col-md-8">
            <span class="stock-item-description">
                <%= for line <- String.split(item.description, "\n") do %>
                    <%= line %><br>
                <% end %>
            </span>
        </div>
        <div class="col-12">
            <span class="stock-item-duration">
                <%= format_duration(item) %>
            </span>
        </div>
    </div>
    <% end %>
</div>

stack/apps/stack/lib/stack_web/templates/stock_item/show.html.eex
<div class="container-fluid stock-item">
    <div class="row">
        <div class="col-12 col-md-4 bg-info text-white text-md-right">備品名</div>
        <div class="col-12 col-md-8"><%= @stock_item.name %></div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4 bg-info text-white text-md-right">説明</div>
        <div class="col-12 col-md-8">
            <%= for line <- String.split(@stock_item.description, "\n") do %>
                <%= line %><br>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4 bg-info text-white text-md-right">なくなった日時</div>
        <div class="col-12 col-md-8">
            <%= Strftime.format!(@stock_item.order_time, "%m月%-d日 %H:%M") %>
        </div>
    </div>
</div>

stack/apps/stack/lib/stack_web/templates/top/index.html.eex
<div>
    <%= link to: Routes.stock_item_path(@conn, :index) do %>
        <i class="fa fa-list"></i>備品一覧
    <% end %>
</div>